Repository semver/semver.org, pull requests merged in 2020-06, with the labels that each got.

#229 Fix small mistake
  lang/ru/spec/v2.0.0.md
Labels: i18n

#217 Fix typos in swedish translation
  lang/sv/index.md
Labels: i18n, waiting for author, waiting for review

#237 Armenian Translation
  _config.yml
  lang/hy/index.md
  lang/hy/spec/v2.0.0-rc.1.md
  lang/hy/spec/v2.0.0-rc.2.md
  lang/hy/spec/v2.0.0.md
Labels: i18n, waiting for author, waiting for review

#238 Update FAQs in Korean documents
  lang/ko/index.md
  lang/ko/spec/v2.0.0.md
Labels: i18n, waiting for review

#242 [Japanese] Fix Japanese translation for slightly better expression
  lang/ja/index.md
  lang/ja/spec/v2.0.0.md
Labels: i18n, waiting for review

#260 Fix typos in the Hungarian translation
  lang/hu/index.md
  lang/hu/spec/v2.0.0.md
Labels: i18n, waiting for review

#253 Fix typo in german translation
  lang/de/spec/v2.0.0.md
Labels: i18n, waiting for review

#243 [Japanese] Update Japanese specification to follow up to 2.0.0
  lang/ja/index.md
  lang/ja/spec/v2.0.0.md
Labels: i18n

#265 Added script to automatically sync between original - website repos
  .github/workflows/sync.yml
  .gitignore
  _config.yml
  package-lock.json
  package.json
  scripts/collect.js
  spec/v2.0.0.md
Labels: build, feature

#245 Added kabyle translation for v2.0.0 spec.
  _config.yml
  lang/kab/index.md
  lang/kab/spec/v2.0.0.md
Labels: i18n

#222 Update _config.yml
  _config.yml
Labels: content, i18n

#268 fix: Updated headers line height and anchor styles
  css/main.css
Labels: bug

#267 fix/anchors
  _layouts/default.html
  css/main.css
  js/anchorli.js
Labels: bug, waiting for review

#244 [GERMAN] add BNF Block to german translation
  lang/de/index.md
  lang/de/spec/v2.0.0.md
Labels: i18n

#258 Update index.md
  lang/sk/index.md
Labels: i18n, waiting for review

#228 Translation document to Vietnamese
  _config.yml
  lang/vi/index.md
  lang/vi/spec/v2.0.0.md
Labels: i18n

#257 Translation/bulgarian
  _config.yml
  lang/bg/index.md
  lang/bg/spec/v2.0.0.md
Labels: i18n

#259 Update v2.0.0.md
  lang/sk/spec/v2.0.0.md
Labels: i18n, waiting for review

#273 Fix markdown link and replacing the URL for create issues
  lang/pt-BR/index.md
Labels: i18n
