Repository semver/semver.org, pull requests merged in 2020-07, with the labels that each got.

#281 [Japanese] fix: Copy lang/ja/index.md to lang/ja/spec/v2.0.0.md
  lang/ja/spec/v2.0.0.md
Labels: i18n

#283 Fix English navigation link to home
  _layouts/default.html
Labels: bug, content

#286 fix: useless 301 redirect
  _layouts/default.html
Labels: bug
